In [25]:
import gym
import matplotlib.pyplot as plt
import collections
import numpy as np

In [2]:
env = gym.make("FrozenLake-v1", is_slippery = True)

In [3]:
env.observation_space.n, env.action_space.n

(16, 4)

In [4]:
env.reset()
env.step(0)

(0, 0.0, False, {'prob': 0.3333333333333333})

In [23]:
env.step(3) # ns, r, done, info

(1, 0.0, False, {'prob': 0.3333333333333333})

* 알고리즘

In [ ]:
class Q_tree():
    def __init__(
        self,
        y_val: np.array,
        x_val: np.array,
        max_depth: int = 10,
        min_sample_leaf: int = 2
    ):
        self.y_val = y_val 
        self.x_val = x_val
        self.n = len(y_val)
        self.depth = 0
        self.max_depth = max_depth
        self.min_sample_leaf = min_sample_leaf

        def get_mean(self,val_array: np.array):
            return np.sum(val_array)/len(val_array)

        def get_mse(self,y_val: np.array):
            mean = self.get_mean(y_val)
            return np.sum((y_val - mean)**2)/len(y_val)

        def get_obj_score(self, left_y: np.array, right_y: np.array):
            _mse_left = self.get_mse(left_y)
            _mse_right = self.get_mse(right_y)
            l_len = len(left_y)
            r_len = len(right_y)
            t_len = l_len + r_len
            return (_mse_left * l_len / t_len) + (_mse_right * r_len / t_len)

        def get_best_split(self):
            _best_mse = None
            #_best_feature = None  frozen lake는 feature 1차원이라 고려 x
            _best_split_value = None

            for i in list(set(self.x_val)):
                right_ind = self.x_val > i
                right_y = self.y_val[right_ind]
                left_y = self.y_val[~right_ind]

                if len(right_y) >= self.min_sample_leaf and len(left_y) >= self.min_sample_leaf:
                    _mse_w = self.get_obj_score(left_y, right_y)

                    if _best_mse is None:
                        _best_mse = _mse_w
                        _best_split_value = i

                    elif _mse_w < _best_mse:
                        _best_mse = _mse_w
                        _best_split_value = i

            self.best_split_value = _best_split_value

        
        def train(self):
            if self.depth < self.max_depth:
                self.get_best_split()
                right_ind = self.x_val > self.best_split_value

                y_r = self.y_val[right_ind]
                y_l = self.y_val[~right_ind]

                x_r = self.x_val[right_ind]
                x_l = self.x_val[~right_ind]

                q_tree_l = Q_tree(y_l, x_l)
                q_tree_r = Q_tree(y_r, x_r)

                q_tree_l.depth += 1
                q_tree_r.depth += 1

                self.left = q_tree_l
                self.right = q_tree_r

                self.left.train()
                self.right.train()

        def predict(self):
            # 나머지 완성





In [42]:
np.array([[1],[2],[3],[4],[3],[6],[7],[8],[10],[11],]) > 3

array([[False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [46]:
ind_t = np.array([[1],[2],[3],[4],[3],[6],[7],[8],[10],[11],]) > 3
np.array([[1],[2],[3],[4],[3],[6],[7],[8],[10],[11],])[~ind_t]

array([1, 2, 3, 3])

In [37]:
np.array([[1,2,3],[4,5,6]])[:,1]

array([2, 5])

In [40]:
np.array([[1,2,3],[4,5,6]])[0,:]

array([1, 2, 3])

In [32]:
np.sum((np.array([1,2,3,4,5,6,]) - 2)**2)

31

In [35]:
np.concatenate([np.array([1,2,3,4,5,6,]),np.array([1,2,3,4,5,6,])])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])